
import java.util.Random;
import java.util.concurrent.CountDownLatch;

public class TestingFramework {

    public static final byte INSERT = 0;
    public static final byte QUERY = 1;
    public static final byte SUCCESSOR = 2;

    public long universe;
    public long[] nums;

    public long[] randomOpKeys;
    public byte[] randomOpTypes;
    public long[] randomNums;

    public TestingFramework(long universe) {
        this.universe = universe;
    }

    public void generateOps(int n) {
        generateOps(n, 0);
    }

    // Generate a variety of operations (total of n operations)(mix between insert,
    // query, successor)
    // fill is just how many elements we want to insert prior to running the tests
    public void generateOps(int n, int fill) {
        Random rng = new Random(1234567);

        // List of numbers to insert before ops
        this.randomNums = new long[fill];
        for (int i = 0; i < fill; i++) {
            this.randomNums[i] = rng.nextLong() & (this.universe - 1);
        }

        // Generate the operations
        this.randomOpKeys = new long[n];
        this.randomOpTypes = new byte[n];
        for (int i = 0; i < n; i++) {
            this.randomOpKeys[i] = rng.nextLong() & (this.universe - 1);
            this.randomOpTypes[i] = (byte) rng.nextInt(3);
        }
    }

    // Runs the operations that are generated by generateOps (a list of operations
    // that are a mix of insert, successor, and queries)
    // ops are pre-partitioned per thread — no shared counter in the hot loop
    public RunResult runRandom(String name, int threadCount, LongOp insertFn, BoolOp queryFn,
            LongResultOp successorFn) {
        // fill before timing
        if (this.randomNums != null) {
            for (int i = 0; i < this.randomNums.length; i++) {
                insertFn.apply(this.randomNums[i]);
            }
        }

        int total = this.randomOpKeys.length;
        int chunkSize = (total + threadCount - 1) / threadCount;

        CountDownLatch startLatch = new CountDownLatch(1);
        CountDownLatch doneLatch = new CountDownLatch(threadCount);

        for (int t = 0; t < threadCount; t++) {
            final int start = t * chunkSize;
            final int end = Math.min(start + chunkSize, total);
            new Thread(() -> {
                try {
                    startLatch.await();
                    for (int i = start; i < end; i++) {
                        long num = randomOpKeys[i];
                        byte op = randomOpTypes[i];
                        if (op == INSERT) {
                            insertFn.apply(num);
                        } else if (op == QUERY) {
                            queryFn.apply(num);
                        } else {
                            successorFn.apply(num);
                        }
                    }
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                } finally {
                    doneLatch.countDown();
                }
            }).start();
        }

        long startTime = System.nanoTime();
        startLatch.countDown();
        try {
            doneLatch.await();
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }
        long endTime = System.nanoTime();

        return new RunResult(
                name + "_" + threadCount + "thread",
                total,
                this.universe,
                (endTime - startTime) / 1e9,
                0,
                0);
    }

    @FunctionalInterface
    public interface LongOp {
        void apply(long x);
    }

    @FunctionalInterface
    public interface BoolOp {
        boolean apply(long x);
    }

    @FunctionalInterface
    public interface LongResultOp {
        Long apply(long x);
    }
}
