
import java.util.Random;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.atomic.AtomicLong;

public class TestingFramework {

    public static final byte INSERT = 0;
    public static final byte QUERY = 1;
    public static final byte SUCCESSOR = 2;

    public long universe;
    public long[] nums;

    public long[] randomOpKeys;
    public byte[] randomOpTypes;
    public long[] randomNums;

    public TestingFramework(long universe) {
        this.universe = universe;
    }

    public void generateNumbers(int n) {
        Random rng = new Random(1234567);
        this.nums = new long[n];
        for (int i = 0; i < n; i++) {
            this.nums[i] = rng.nextLong() & (this.universe - 1);
        }
    }

    public void generateOps(int n) {
        generateOps(n, 0);
    }

    // Generate a variety of operations (total of n operations)(mix between insert,
    // query, successor)
    // fill is just how many elements we want to insert prior to running the tests
    public void generateOps(int n, int fill) {
        Random rng = new Random(1234567);

        // List of numbers to insert before ops
        this.randomNums = new long[fill];
        for (int i = 0; i < fill; i++) {
            this.randomNums[i] = rng.nextLong() & (this.universe - 1);
        }

        // Generate the operations
        this.randomOpKeys = new long[n];
        this.randomOpTypes = new byte[n];
        for (int i = 0; i < n; i++) {
            this.randomOpKeys[i] = rng.nextLong() & (this.universe - 1);
            this.randomOpTypes[i] = (byte) rng.nextInt(3);
        }
    }

    // Times insert, query, and successor independently of each other, each
    // operation is ran n times
    public RunResult runBasic(String name, int threadCount, LongOp insertFn, BoolOp queryFn, LongResultOp successorFn) {
        double insertTimeSeconds;
        double queryTimeSeconds;
        double successorTimeSeconds;

        insertTimeSeconds = runPhase(threadCount, this.nums.length, (i) -> insertFn.apply(this.nums[i]));
        queryTimeSeconds = runPhase(threadCount, this.nums.length, (i) -> queryFn.apply(this.nums[i]));
        successorTimeSeconds = runPhase(threadCount, this.nums.length, (i) -> successorFn.apply(this.nums[i]));

        return new RunResult(
                name + "_" + threadCount + "thread",
                this.nums.length,
                this.universe,
                insertTimeSeconds,
                queryTimeSeconds,
                successorTimeSeconds);
    }

    // Runs the operations that are generated by generateOps (a list of operations
    // that are a mix of insert, successor, and queries)
    public RunResult runRandom(String name, int threadCount, LongOp insertFn, BoolOp queryFn,
            LongResultOp successorFn) {
        // Fill is just how many elements we want to insert prior to running the tests
        if (this.randomNums != null) {
            for (int i = 0; i < this.randomNums.length; i++) {
                insertFn.apply(this.randomNums[i]);
            }
        }

        double totalTime = runPhase(threadCount, this.randomOpKeys.length, (i) -> {
            long num = this.randomOpKeys[i];
            byte op = this.randomOpTypes[i];
            if (op == INSERT) {
                insertFn.apply(num);
            } else if (op == QUERY) {
                queryFn.apply(num);
            } else {
                successorFn.apply(num);
            }
        });

        return new RunResult(
                name + "_" + threadCount + "thread",
                this.randomOpKeys.length,
                this.universe,
                totalTime,
                0,
                0);
    }

    public double runPhase(int threadCount, long n, IndexOp workFn) {

        CountDownLatch startLatch = new CountDownLatch(1);
        CountDownLatch doneLatch = new CountDownLatch(threadCount);
        AtomicLong nextIndex = new AtomicLong(0);

        for (int threadId = 0; threadId < threadCount; threadId++) {
            Thread thread = new Thread(() -> {
                try {
                    startLatch.await();
                    while (true) {
                        long i = nextIndex.getAndIncrement();
                        if (i >= n) {
                            break;
                        }
                        workFn.apply((int) i);
                    }
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                } finally {
                    doneLatch.countDown();
                }
            });
            thread.start();
        }

        long startTime = System.nanoTime();
        startLatch.countDown();

        try {
            doneLatch.await();
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }

        long endTime = System.nanoTime();
        return (endTime - startTime) / 1e9;
    }

    @FunctionalInterface
    public interface LongOp {

        void apply(long x);
    }

    @FunctionalInterface
    public interface BoolOp {

        boolean apply(long x);
    }

    @FunctionalInterface
    public interface LongResultOp {

        Long apply(long x);
    }

    @FunctionalInterface
    public interface IndexOp {

        void apply(int i);
    }
}
