import java.util.Random;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.atomic.AtomicInteger;

public class TestingFramework {
    enum OPType {INSERT, QUERY, SUCCESSOR}

    static class Ops {
        OPType op;
        int number;
        Ops(OPType op, int number) {
            this.op = op;
            this.number = number;
        }
    }

    public int universe;
    public int[] nums;

    public Ops[] randomOps;
    public int[] randomNums;
    public static final OPType[] ops = { OPType.INSERT, OPType.QUERY, OPType.SUCCESSOR };

    public TestingFramework(int universe) {
        this.universe = universe;
    }

    public void generateNumbers(int n) {
        Random rng = new Random(1234567);
        this.nums = new int[n];
        for (int i = 0; i < n; i++) {
            this.nums[i] = rng.nextInt(this.universe);
        }
    }

    public void generateOps(int n){
        generateOps(n, 0);
    }

    // Generate a variety of operations (total of n operations)(mix between insert, query, successor)
    // fill is just how many elements we want to insert prior to running the tests
    public void generateOps(int n, int fill){
        Random rng = new Random(1234567);

        // List of numbers to insert before ops
        this.randomNums = new int[fill];
        for (int i = 0; i < fill; i++) {
            this.randomNums[i] = rng.nextInt(this.universe);
        }

        // Generate the operations
        this.randomOps = new Ops[n];
        for (int i = 0; i < n; i++) {
            OPType op = ops[rng.nextInt(ops.length)];
            int num = rng.nextInt(this.universe);
            this.randomOps[i] = new Ops(op, num);
        }
    }

    // Times insert, query, and successor independently of each other, each operation is ran n times
    public RunResult runBasic(String name, int threadCount, IntOp insertFn, BoolOp queryFn, IntResultOp successorFn) {
        double insertTimeSeconds;
        double queryTimeSeconds;
        double successorTimeSeconds;

        insertTimeSeconds = runPhase(threadCount, this.nums.length, (i) -> insertFn.apply(this.nums[i]));
        queryTimeSeconds  = runPhase(threadCount, this.nums.length, (i) -> queryFn.apply(this.nums[i]));
        successorTimeSeconds = runPhase(threadCount, this.nums.length, (i) -> successorFn.apply(this.nums[i]));

        return new RunResult(
                name + "_" + threadCount + "thread",
                this.nums.length,
                this.universe,
                insertTimeSeconds,
                queryTimeSeconds,
                successorTimeSeconds
        );
    }

    // Runs the operations that are generated by generateOps (a list of operations that are a mix of insert, successor, and queries)
    public RunResult runRandom(String name, int threadCount, IntOp insertFn, BoolOp queryFn, IntResultOp successorFn) {
        // Fill is just how many elements we want to insert prior to running the tests
        if (this.randomNums != null) {
            for (int i = 0; i < this.randomNums.length; i++) {
                insertFn.apply(this.randomNums[i]);
            }
        }

        double totalTime = runPhase(threadCount, this.randomOps.length, (i) -> {
            Ops op = this.randomOps[i];
            if (op.op == OPType.INSERT) {
                insertFn.apply(op.number);
            } else if (op.op == OPType.QUERY) {
                queryFn.apply(op.number);
            } else {
                successorFn.apply(op.number);
            }
        });

        return new RunResult(
                name + "_" + threadCount + "thread",
                this.randomOps.length,
                this.universe,
                totalTime,
                0,
                0
        );
    }

    public double runPhase(int threadCount, int n, IndexOp workFn) {

        CountDownLatch startLatch = new CountDownLatch(1);
        CountDownLatch doneLatch = new CountDownLatch(threadCount);
        AtomicInteger nextIndex = new AtomicInteger(0);

        for (int threadId = 0; threadId < threadCount; threadId++) {
            Thread thread = new Thread(() -> {
                try {
                    startLatch.await();
                    while (true) {
                        int i = nextIndex.getAndIncrement();
                        if (i >= n) break;
                        workFn.apply(i);
                    }
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                } finally {
                    doneLatch.countDown();
                }
            });
            thread.start();
        }

        long startTime = System.nanoTime();
        startLatch.countDown();

        try {
            doneLatch.await();
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }

        long endTime = System.nanoTime();
        return (endTime - startTime) / 1e9;
    }

    @FunctionalInterface
    public interface IntOp {
        void apply(int x);
    }

    @FunctionalInterface
    public interface BoolOp {
        boolean apply(int x);
    }

    @FunctionalInterface
    public interface IntResultOp {
        Integer apply(int x);
    }

    @FunctionalInterface
    public interface IndexOp {
        void apply(int i);
    }
}